# vim:ft=kitty

## name: Edna-Light 
## author: Julian (http://github.com/nan0bug00)
## license: MIT
## upstream: Konsole Scheme Edna-Light by Jorge Dangelo (https://store.kde.org/p/152895)
## blurb: Direct conversion attempt of Edna-Light Konsole Scheme

# Core Colors from Konsole Scheme

background                #c4c8ce
foreground                #2a2d31
background_opacity 0.9
background_blur 64
background_tint 30

# ANSI Colors
color0                    #455c67
color1                    #d54f8b
color2                    #0c8d75
color3                    #df815e
color4                    #2882cb
color5                    #ba6ee7
color6                    #00999e
color7                    #6f91a0

# Intense ANSI Colors
color8                    #3b4e57
color9                    #c0487e
color10                   #0c8672
color11                   #ce7757
color12                   #257abf
color13                   #af66d6
color14                   #009193
color15                   #698897

# Derived / Subjective Values (Adjust as needed)
selection_background      #c4c8ce
selection_foreground      #1e2123

url_color                 #2882cb
url_style curly

cursor                    #2a2d31
cursor_text_color         #c4c8ce

# Kept from your original file / Kitty Specific UI (Adjust as needed)
wayland_titlebar_color    system
macos_titlebar_color      system
active_border_color       #c0bfbc
inactive_border_color     #f6f5f4
bell_border_color         #ed333b
visual_bell_color         none
tab_bar_background        #10a6d4
inactive_tab_background   #10a6d4
inactive_tab_foreground   #ccd0d6
active_tab_background     #ccd0d6
active_tab_foreground     #2a2d31
tab_bar_margin_color      none

